### ISSUE TITLE
I didn't got why this issue is happening can anyone identify ?

### ISSUE THREAD

**Issue by iNuman** [s4ysolutions/itag#66]
**The app build successfully but when I hit run this issue occurred:**
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.maddevsio.mad-location-manager:mad-location-manager:0.1.14.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/maddevsio/mad-location-manager/mad-location-manager/0.1.14/mad-location-manager-0.1.14.pom
       - https://jcenter.bintray.com/com/maddevsio/mad-location-manager/mad-location-manager/0.1.14/mad-location-manager-0.1.14.pom
       - file:/C:/Users/Adnan/.m2/repository/com/maddevsio/mad-location-manager/mad-location-manager/0.1.14/mad-location-manager-0.1.14.pom
       - https://maven.google.com/com/maddevsio/mad-location-manager/mad-location-manager/0.1.14/mad-location-manager-0.1.14.pom
       - https://jitpack.io/com/maddevsio/mad-location-manager/mad-location-manager/0.1.14/mad-location-manager-0.1.14.pom
     Required by:
         project :app > solutions.s4y.waytoday:waytoday-sdk:1.0.32

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by john1364** [comment]
https://github.com/s4ysolutions/WayTodaySDK-Android

> Currently the 3rd party dependency mad-location-manager:0.1.14 is not uploaded to a public repo and you have to clone the fork https://github.com/s4ysolutions/mad-location-manager and issue ./gradlew publishToMavenLocal

**Comment by lucasresck** [comment]
I had a similar problem with the dependency `mad-location-manager`, however I couldn't build the app at all. I managed to solve it and I would like to complement @john1364's answer.

On a terminal, clone and enter the dependency `mad-location-manager` repository:
```
https://github.com/s4ysolutions/mad-location-manager
cd mad-location-manager
```
If using Android Studio in Ubuntu 22.04 (or similar), export relevant environmental variables:
```
export JAVA_HOME='/path/to/android-studio/jre'  # In my case, '/home/user/android-studio/jre'
export ANDROID_SDK_ROOT='/path/to/Android/Sdk'  # In my case, '/home/user/Android/Sdk'
```
Perform the following commands:
```
./gradlew clean
./gradlew build 
./gradlew publishToMavenLocal
```

**Comment by fluffyspace** [comment]
@lucasresck Thank you. This worked for me but I had to use Java 11.
