### ISSUE TITLE
File google-services.json is missing. Can anyone help?

### ISSUE THREAD

**Issue by Liyana-Azman** [s4ysolutions/itag#70]
Hi, I faced this issue. I already added the google-services.json file based on a tutorial I found, but it doesn’t work.

**Error:**
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. 
  The Google Services Plugin cannot function without it.

**Comment by dsame** [comment]
Put it into app, app/src, etc until it is patched up
